# https://github.com/actions/create-release

on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0

      - run: git fetch --tags -f

      - id: git-history
        run: |
          # get previous tag
          REF=$(git describe --abbrev=0 ${{ github.ref }}^)
          # commits between now and previous tag
          LOG=`git log --pretty=format:"- %h %s - %cn" ${{ github.ref }}...refs/tags/$REF^`

          # multiline fix
          LOG="${LOG//'%'/'%25'}"
          LOG="${LOG//$'\n'/'%0A'}"
          LOG="${LOG//$'\r'/'%0D'}"

          echo "::set-output name=text::$(echo "$LOG")"

      - name: Create Release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Commits
            ${{ steps.git-history.outputs.text }}
          draft: false
          prerelease: false
